import 'package:flutter/material.dart';

const K_PRIMARY_COLOR = Color(0xFF888888);

const K_TEXT_COLOR = Color(0xFF888888);

const K_BACKGROUND_COLOR = Color(0xFFF9F8FD);

const K_CARD_BACKGROUND_COLOR = Color(0xFFDCDCDC);

const K_SECONDARY_COLOR = Color(0xFFFE9901);

const K_CONTENT_COLOR_LIGHT_THEME = Color(0xFF1D1D35);
const K_CONTENT_COLOR_DARK_THEME = Color(0xFFF5FCF9);

const K_WARNINNG_COLOR = Color(0xFFF3BB1C);
const K_ERROR_COLOR = Color(0xFFF03738);

const K_DEFAULT_PADDING = 20.0;

const D_PRIMARY_COLOR = Color.fromARGB(255, 72, 148, 236);
